
2022-11-18-12.10.05.372544+330 I1E1376              LEVEL: Event
PID     : 24351                TID : 140704639624384PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: nitin-pt5603
FUNCTION: DB2 UDB, RAS/PD component, pdLogInternal, probe:120
START   : New Diagnostic Log file
DATA #1 : Build Level, 240 bytes
Instance "DB2" uses "64" bits and DB2 code release "SQL11056"
with level identifier "0607010F".
Informational tokens are "DB2 v11.5.6.0", "special_15427", "DYN2203041544MAC_15427", Fix Pack "0".
DATA #2 : System Info, 1760 bytes
System: Darwin nitin-pt5603 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64 x86_64
CPU: total:12 online:12 Threading degree per core:1 SIMD:N CPU Features:SSE2,SSE3,SSSE3,SSE4,AVX2
Physical Memory(MB): total:14543 free:6029
Virtual  Memory(MB): total:14543 free:6029
Swap     Memory(MB): total:0 free:0
Cur cpu time limit (seconds)  = 0x7FFFFFFFFFFFFFFF
Cur file size limit (bytes) = 0x7FFFFFFFFFFFFFFF
Cur data size (bytes)  = 0x7FFFFFFFFFFFFFFF
Cur stack size (bytes)  = 0x0000000000800000
Cur core size (bytes)  = 0x0000000000000000
Cur memory size (bytes) = 0x7FFFFFFFFFFFFFFF
nofiles (descriptors)  = 0x0000000000001C00
Disk: 4K Device Support: NONE

Information in this record is only valid at the time when this file was
created (see this record's time stamp)

2022-11-18-12.10.05.372756+330 I1378E366            LEVEL: Error
PID     : 24351                TID : 140704639624384PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: nitin-pt5603
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:42
MESSAGE : DIA3222E The host name "" was not found, TCP/IP function "" error 
          return code = "".

2022-11-18-12.10.05.374523+330 I1745E627            LEVEL: Severe
PID     : 24351                TID : 140704639624384PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: nitin-pt5603
FUNCTION: DB2 UDB, DRDA Communication Manager, sqljcCommConnect, probe:10
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 11 bytes
CCI Error: 
DATA #2 : unsigned integer, 8 bytes
97
CALLSTCK: (Static functions may not be resolved correctly, as they are resolved to the nearest symbol)
  [0] 0x0000000000000000 ?unknown + 0x0
  [1] 0x0000000000000000 ?unknown + 0x0

2022-11-18-12.10.40.995735+330 I2373E366            LEVEL: Error
PID     : 24439                TID : 140704639624384PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: nitin-pt5603
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:42
MESSAGE : DIA3222E The host name "" was not found, TCP/IP function "" error 
          return code = "".

2022-11-18-12.10.41.000120+330 I2740E627            LEVEL: Severe
PID     : 24439                TID : 140704639624384PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: nitin-pt5603
FUNCTION: DB2 UDB, DRDA Communication Manager, sqljcCommConnect, probe:10
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 11 bytes
CCI Error: 
DATA #2 : unsigned integer, 8 bytes
97
CALLSTCK: (Static functions may not be resolved correctly, as they are resolved to the nearest symbol)
  [0] 0x0000000000000000 ?unknown + 0x0
  [1] 0x0000000000000000 ?unknown + 0x0

2022-11-18-12.10.54.917514+330 I3368E366            LEVEL: Error
PID     : 24490                TID : 140704639624384PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: nitin-pt5603
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:42
MESSAGE : DIA3222E The host name "" was not found, TCP/IP function "" error 
          return code = "".

2022-11-18-12.10.54.918472+330 I3735E627            LEVEL: Severe
PID     : 24490                TID : 140704639624384PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: nitin-pt5603
FUNCTION: DB2 UDB, DRDA Communication Manager, sqljcCommConnect, probe:10
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 11 bytes
CCI Error: 
DATA #2 : unsigned integer, 8 bytes
97
CALLSTCK: (Static functions may not be resolved correctly, as they are resolved to the nearest symbol)
  [0] 0x0000000000000000 ?unknown + 0x0
  [1] 0x0000000000000000 ?unknown + 0x0

2022-11-18-12.13.10.912527+330 I4363E366            LEVEL: Error
PID     : 24695                TID : 140704639624384PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: nitin-pt5603
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:42
MESSAGE : DIA3222E The host name "" was not found, TCP/IP function "" error 
          return code = "".

2022-11-18-12.13.10.913179+330 I4730E627            LEVEL: Severe
PID     : 24695                TID : 140704639624384PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: nitin-pt5603
FUNCTION: DB2 UDB, DRDA Communication Manager, sqljcCommConnect, probe:10
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 11 bytes
CCI Error: 
DATA #2 : unsigned integer, 8 bytes
97
CALLSTCK: (Static functions may not be resolved correctly, as they are resolved to the nearest symbol)
  [0] 0x0000000000000000 ?unknown + 0x0
  [1] 0x0000000000000000 ?unknown + 0x0

2022-11-18-12.17.59.425610+330 I5358E366            LEVEL: Error
PID     : 25129                TID : 140704639624384PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: nitin-pt5603
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:42
MESSAGE : DIA3222E The host name "" was not found, TCP/IP function "" error 
          return code = "".

2022-11-18-12.17.59.426643+330 I5725E627            LEVEL: Severe
PID     : 25129                TID : 140704639624384PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: nitin-pt5603
FUNCTION: DB2 UDB, DRDA Communication Manager, sqljcCommConnect, probe:10
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 11 bytes
CCI Error: 
DATA #2 : unsigned integer, 8 bytes
97
CALLSTCK: (Static functions may not be resolved correctly, as they are resolved to the nearest symbol)
  [0] 0x0000000000000000 ?unknown + 0x0
  [1] 0x0000000000000000 ?unknown + 0x0

2022-11-18-12.22.08.463204+330 I6353E424            LEVEL: Warning
PID     : 25410                TID : 140704639624384PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: nitin-pt5603
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:14
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 30 bytes
Client Reroute is starting....

2022-11-18-12.22.08.468179+330 I6778E490            LEVEL: Warning
PID     : 25410                TID : 140704639624384PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: nitin-pt5603
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 15 bytes
158.175.131.250
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30120

2022-11-18-12.23.22.001595+330 I7269E424            LEVEL: Warning
PID     : 25549                TID : 140704639624384PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: nitin-pt5603
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:14
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 30 bytes
Client Reroute is starting....

2022-11-18-12.23.22.011175+330 I7694E489            LEVEL: Warning
PID     : 25549                TID : 140704639624384PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: nitin-pt5603
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 14 bytes
141.125.88.202
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30120

2022-11-18-12.24.22.409693+330 I8184E424            LEVEL: Warning
PID     : 25658                TID : 140704639624384PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: nitin-pt5603
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:14
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 30 bytes
Client Reroute is starting....

2022-11-18-12.24.22.411350+330 I8609E489            LEVEL: Warning
PID     : 25658                TID : 140704639624384PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: nitin-pt5603
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 14 bytes
158.176.91.122
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30120

2022-11-18-12.25.49.363992+330 I9099E424            LEVEL: Warning
PID     : 25898                TID : 140704639624384PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: nitin-pt5603
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:14
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 30 bytes
Client Reroute is starting....

2022-11-18-12.25.49.366477+330 I9524E490            LEVEL: Warning
PID     : 25898                TID : 140704639624384PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: nitin-pt5603
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 15 bytes
158.175.131.250
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30120

2022-11-18-12.28.20.652419+330 I10015E331           LEVEL: Error
PID     : 26033                TID : 140704639624384PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: nitin-pt5603
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="60".

2022-11-18-12.28.39.681993+330 I10347E424           LEVEL: Warning
PID     : 26033                TID : 140704639624384PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: nitin-pt5603
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:14
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 30 bytes
Client Reroute is starting....

2022-11-18-12.28.39.683477+330 I10772E489           LEVEL: Warning
PID     : 26033                TID : 140704639624384PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: nitin-pt5603
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 14 bytes
158.176.91.122
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
50000

2022-11-18-23.38.04.497913+330 I11262E424           LEVEL: Warning
PID     : 44277                TID : 140704639624384PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: nitin-pt5603
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:14
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 30 bytes
Client Reroute is starting....

2022-11-18-23.38.04.499980+330 I11687E490           LEVEL: Warning
PID     : 44277                TID : 140704639624384PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: nitin-pt5603
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 15 bytes
158.175.131.250
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30120
